Fix migration of 0.15.2
This was causing the following error to occur when consenting:

 equelizeDatabaseError: there is no unique or exclusion constraint
 matching the ON CONFLICT specification